/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_FULLCONTROLTEST
#define VCZH_WORKFLOW_COMPILER_GENERATED_FULLCONTROLTEST

#include "FullControlTestPartialClasses.h"
#include "DocumentEditorBase.h"
#include "MainWindow.h"
#include "FullControlTestPartialClasses1.h"

#endif
