/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_TUICONTROLTEST
#define VCZH_WORKFLOW_COMPILER_GENERATED_TUICONTROLTEST

#include "TuiControlTestPartialClasses.h"

#endif
