/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_REMOTEPROTOCOLTEST
#define VCZH_WORKFLOW_COMPILER_GENERATED_REMOTEPROTOCOLTEST

#include "RemoteProtocolTestPartialClasses.h"
#include "ClickMeTab.h"
#include "DataGridTab.h"
#include "DocumentTab.h"
#include "RpMainWindow.h"

#endif
